version: 1
formatters:
  default:
    format: "%(asctime)s, %(levelname)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  werkzeug:
    format: "%(asctime)s, %(levelname)s: Flask/Werkzeug log: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
  werkzeug:
    class: logging.StreamHandler
    formatter: werkzeug
    level: INFO
root:
  level: INFO
  handlers: [default]
loggers:
  log:
    handlers: [default]
    level: INFO
    propagate: False
  werkzeug:
    handlers: [werkzeug]
    level: INFO
    propagate: False
