version: 1
formatters:
  default:
    format: "%(asctime)s, %(levelname)s, %(name)s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
  json:
    (): modules.custom_logger.JsonFormatter
    fmt_keys:
      timestamp: timestamp
      level: levelname
      logger: name
      module: module
      function: funcName
      line: lineno
      message: message
      thread_name: threadName
handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    level: ERROR
    filename: "exchange_rate_viewer/logs/errors_log.log"
    maxBytes: 10240 # 10KB
    backupCount: 3
root:
  level: INFO
  handlers: [default, file]
loggers:
  app_logger:
    handlers: [default, file]
    level: INFO
    propagate: False
  werkzeug:
    handlers: [default, file]
    level: INFO
    propagate: False
